### ISSUE TITLE
MVP1 - User Auth

### ISSUE THREAD

**Issue by RawBData** [RawBData/Checkoff#3]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [ ] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

## Seeds
- [x] Adequate and appropriate seeds

**Comment by jenkennedy** [comment]
- [ ] Update link on Wiki Home page to your live site
- [ ] `/splash` should just be `/` for frontend route when rendering `Splash` component
- [ ] Create color inverted logo so your logo is not a white rectangle (text and images in it are white and background is transparent)
### Log In & Sign Up
- [ ] Fix aspect ratio of logo on Session pages
- [ ] Use the same font Remember the Milk uses
- [ ] Increase height of sign up button to match button size of Remember the Milk
- [ ] Add demo login button to Login Page and style it like the Facebook or Google button with the --or-- in between to make it look like Remember the milk and POP
- [ ] Align the link / button to switch between sign up and login pages so that it doesn't go any farther left that the left most part of your form (Remember the Milk has it aligned with their form - probably in the same container)
- [ ] Reduce font size, reduce font weight, and add padding around text inside button / link between login and sign up pages
- [ ] Keep all of the quote text on the login page white, update the font, add quotation marks around the quote (will probably have to `\` escape them for JS to not freak out)
- [ ] Remove the white space showing around the grey half of the page (top, left, and bottom)
- [ ] Change border around input boxes on sign up and login pages to be a light grey and same color all the way around to keep a cleaner look
- [ ] When typing in information in the session form, every letter i type changes the quote on the left.  Fix this to where it only shuffles every time the form mounts instead of every time the input is changed

### NavBar
- [ ]

**Comment by jenkennedy** [comment]
AWESOME updates Ben! Site is looking really clean and professional.  Went ahead and checked off items that look done.

**Comment by jenkennedy** [comment]
- [ ] Remove the color transition on the font on the splash page and probably the header too.  There is a lot of color changing happening on the page
- [ ] Fix the small "jumping" of the faces appearing on the session form images (I imagine this could be time consuming so I would just remove for now unless its a quick fix)
